name: Python CI for ${{ github.actor }}

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.9'

jobs:
  python-ci:
    name: Python CI
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Display user and commit info
    - name: Display run information
      run: |
        echo "🚀 Workflow triggered by: $GITHUB_ACTOR"
        echo "🔗 Commit SHA: $GITHUB_SHA"
        echo "🌿 Branch: $GITHUB_REF_NAME"
        echo "🎯 Event: $GITHUB_EVENT_NAME"

    # Step 3: Set up Python
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install coverage flake8

    # Step 5: Run Django tests with coverage
    - name: Run Django tests with coverage
      run: |
        echo "=== RUNNING DJANGO TESTS ==="
        if [ -d "tests" ] || [ -f "manage.py" ]; then
          # Using Django test runner
          coverage run manage.py test
        else
          echo "No tests directory or manage.py found. Creating sample test..."
          mkdir -p tests
          echo "def test_example():" > tests/test_sample.py
          echo "    assert 1 + 1 == 2" >> tests/test_sample.py
          coverage run -m pytest tests/ -v
        fi

    # Step 6: Generate coverage report
    - name: Generate coverage report
      run: |
        echo "=== GENERATING COVERAGE REPORT ==="
        coverage html
        coverage xml
        coverage report -m

    # Step 7: Display coverage report in console
    - name: Display coverage report
      run: |
        echo "=== CODE COVERAGE REPORT ==="
        coverage report
        echo "============================"

    # Step 8: Check code style with flake8 (continue on error)
    - name: Check code style
      run: |
        echo "=== FLAKE8 CODE STYLE CHECK ==="
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        echo "==============================="
      continue-on-error: true

    # Step 9: Check code complexity (continue on error)
    - name: Check code complexity
      run: |
        echo "=== CODE COMPLEXITY CHECK ==="
        flake8 . --count --max-complexity=10 --exit-zero --statistics
        echo "============================="
      continue-on-error: true

    # Step 10: Upload Python code as artifact (including nested directories)
    - name: Upload Python code as artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-code-${{ github.sha }}
        path: |
          **/*.py
          requirements.txt
          manage.py
          tests/
        retention-days: 5

    # Step 11: Upload coverage reports as artifact
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports-${{ github.sha }}
        path: |
          htmlcov/
          coverage.xml
        retention-days: 5